name: hme
favicon: null
layout_spectrum: 0.8703029183670878
typography_spectrum: 0.80948
title: Hokkaido Mountain Experience
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f3f4f3'
    - '#94aac3'
    - '#444447'
    - '#1073b5'
    - '#e81917'
  brandStrength: 0.7380041230935603
  lightness: 0.1999798328615725
  saturation: 0.5977832351345569
  rhythmicContrast: 0.9981251256540418
purpose: []
